env:
    browser: true
    es6: true
    mocha: true
    node: true
extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:@typescript-eslint/recommended
root: true
parser: '@typescript-eslint/parser'
settings:
    react:
        version: detect
parserOptions:
    ecmaFeatures:
        jsx: true
    project: './tsconfig.json'
plugins:
    - react
    - '@typescript-eslint'
rules:
    indent: off
    no-undef: off
    'react/display-name': off
    '@typescript-eslint/prefer-interface': off
    '@typescript-eslint/member-delimiter-style': off
    '@typescript-eslint/no-explicit-any': off
    '@typescript-eslint/explicit-function-return-type': off
    '@typescript-eslint/no-use-before-define': off
    '@typescript-eslint/no-unused-vars': [2, { 'argsIgnorePattern': '^_', 'varsIgnorePattern': '^_'}]
    '@typescript-eslint/no-object-literal-type-assertion': off
    '@typescript-eslint/no-floating-promises': [2, {ignoreVoid: true, ignoreIIFE: false}]
    '@typescript-eslint/explicit-module-boundary-types': off
    'no-console': 2
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - never
overrides:
    - files: 
        - '**/*.spec.ts'
        - '**/*.spec.tsx'
      rules:
          '@typescript-eslint/no-non-null-assertion': off
          '@typescript-eslint/no-empty-function': off
          no-undef: off
          no-unused-expressions: off
          max-len: off
          quotes: off
